repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [ '--allow-multiple-documents' ]
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
      - id: pretty-format-json
        args: [ '--autofix', '--indent=2' ]


  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        args: [ '--line-length=88' ]
        files: '^PythonApp/.*\.py$'


  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ '--profile=black', '--line-length=88' ]
        files: '^PythonApp/.*\.py$'


  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [ '--max-line-length=88', '--extend-ignore=E203,W503' ]
        files: '^PythonApp/.*\.py$'
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        files: '^PythonApp/src/.*\.py$'
        additional_dependencies:
          - types-requests
          - types-PyYAML
        args: [ '--ignore-missing-imports', '--strict' ]


  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ '-c', 'pyproject.toml' ]
        additional_dependencies: [ 'bandit[toml]' ]
        files: '^PythonApp/src/.*\.py$'


  - repo: https://github.com/jlleitschuh/ktlint-gradle
    rev: v11.6.1
    hooks:
      - id: ktlint
        files: '^AndroidApp/.*\.kt$'
        args: [ '--android' ]


  - repo: https://github.com/gradle/wrapper-validation-action
    rev: v1.1.0
    hooks:
      - id: gradle-wrapper-validation


  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [ '-d', 'relaxed' ]
        files: '\.(yaml|yml)$'


  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: [ '--fix' ]
        files: '\.md$'


  - repo: https://github.com/errata-ai/vale
    rev: v2.29.7
    hooks:
      - id: vale
        args: [ '--config=.vale.ini' ]
        files: '\.md$'


  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        files: '\.(sh|bash)$'


  - repo: https://github.com/lucas-c/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
        files: 'requirements.*\.txt$'


  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports
        files: '^PythonApp/.*\.py$'


default_language_version:
  python: python3.9


fail_fast: false


exclude: |
  (?x)^(
    .*\.min\.js|
    .*\.min\.css|
    build/|
    dist/|
    \.gradle/|
    .*\.egg-info/|
    htmlcov/|
    \.coverage|
    \.pytest_cache/|
    \.mypy_cache/|
    \.tox/
  )$