name: Integration Testing

on:
  schedule:
    # Run nightly at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  extended-integration-tests:
    name: Extended Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r test-requirements.txt
    
    - name: Run extended test suite
      run: |
        # Use unified testing framework for extended tests
        if [ -f "tests_unified/runners/run_unified_tests.py" ]; then
          echo "Running extended test suite via unified framework..."
          python tests_unified/runners/run_unified_tests.py --mode research --all-levels --extended --durations=10 || echo "::warning::Some extended tests failed"
        else
          echo "::warning::Unified test framework not found, falling back to legacy extended testing"
          
          # Run legacy tests if directories exist
          TEST_DIRS=""
          [ -d "tests/" ] && TEST_DIRS="$TEST_DIRS tests/"
          [ -d "evaluation_suite/" ] && TEST_DIRS="$TEST_DIRS evaluation_suite/"
          
          if [ -n "$TEST_DIRS" ]; then
            pytest $TEST_DIRS -v --tb=short --durations=10 || echo "::warning::Some extended tests failed"
          else
            echo "::warning::No test directories found for extended testing"
          fi
        fi
    
    - name: Run architecture enforcement tests
      run: |
        if [ -f "tests_unified/runners/run_unified_tests.py" ]; then
          echo "Running architecture enforcement tests via unified framework..."
          python tests_unified/runners/run_unified_tests.py --category evaluation --architecture-validation || echo "::warning::Architecture enforcement tests failed"
        else
          echo "::warning::Unified test framework not found, falling back to legacy architecture tests"
          
          if [ -f "PythonApp/test_architecture_enforcement.py" ]; then
            python PythonApp/test_architecture_enforcement.py || echo "::warning::Architecture enforcement tests failed"
          else
            echo "::warning::Architecture enforcement test not found, skipping"
          fi
        fi
    
    - name: Run calibration implementation tests
      run: |
        if [ -f "tests_unified/runners/run_unified_tests.py" ]; then
          echo "Running calibration tests via unified framework..."
          python tests_unified/runners/run_unified_tests.py --category hardware --calibration-tests || echo "::warning::Calibration implementation tests failed"
        else
          echo "::warning::Unified test framework not found, falling back to legacy calibration tests"
          
          if [ -f "PythonApp/test_calibration_implementation.py" ]; then
            python PythonApp/test_calibration_implementation.py || echo "::warning::Calibration implementation tests failed"
          else
            echo "::warning::Calibration implementation test not found, skipping"
          fi
        fi