name: Integration Testing

on:
  schedule:
    # Run nightly at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  extended-integration-tests:
    name: Extended Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r test-requirements.txt
    
    - name: Run extended test suite
      run: |
        pytest tests/ evaluation_suite/ -v --tb=short --durations=10
    
    - name: Run architecture enforcement tests
      run: |
        python PythonApp/test_architecture_enforcement.py
    
    - name: Run calibration implementation tests
      run: |
        python PythonApp/test_calibration_implementation.py