name: Integration Testing

on:
  schedule:
    # Run nightly at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  extended-integration-tests:
    name: Extended Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r test-requirements.txt
    
    - name: Run extended test suite with unified framework
      run: |
        # Use unified testing framework for extended tests
        echo "Running extended test suite via unified framework..."
        python tests_unified/runners/run_unified_tests.py --mode research --all-levels --extended --durations=10
    
    - name: Run architecture enforcement tests with unified framework
      run: |
        echo "Running architecture enforcement tests via unified framework..."
        python tests_unified/runners/run_unified_tests.py --category evaluation --architecture-validation
    
    - name: Run calibration implementation tests with unified framework
      run: |
        echo "Running calibration tests via unified framework..."
        python tests_unified/runners/run_unified_tests.py --category hardware --calibration-tests